#Local config Setting
logging:
  level:
    root: info
server:
  port: 4670
spring:
#Only use.. native profile
  profiles: native
  devtools:
    add-properties: false
  cloud:
    config:
      server:
        #required
        bootstrap: true
        native:
          search-locations: file:///C:\Users\kuh77\git\Msa-config
