logging:
  level:
    root: info
server:
  port: 4670
spring:
  profiles: dev
  devtools:
    add-properties: false
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kuh7770/msa-config






