server:
  port: 4670

spring:
  #profiles:
    #active: operation
    #active: dev
    #active: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kuh7770/msa-config